---
title: Pop Shop
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'This is Pop Shop. What''s happening in NYC.

'
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
